apiVersion: v2
description: >
  Helm chart for fun-bag-agent
  capabilities for the Qlik.
name: fun-bag-agent
version: 0.1.1
keywords:
  - fun-bag-agent
home: https://www.qlik.com
sources:
  - https://github.com/qlik-trial/fun-bag-agent
dependencies:
  - name: qlikcommon
    version: 3.26.2
    repository: oci://ghcr.io/qlik-trial/helm
    condition: global.component-common-imports
