apiVersion: qlik.com/v1
kind: HelmChart
metadata:
  name: fun-bag-agent
chartHome: ../chart
chartName: fun-bag-agent
releaseName: fun-bag-agent
releaseNamespace: $(NAMESPACE)
newChartVersion: $(VERSION)
values:
  image:
    tag: $(VERSION)
